### ISSUE TITLE
Asking for The pretrain checkpoint

### ISSUE THREAD

**Issue by JulieCarlon** [GuodongQi/FSL-OM#1]
Hi, I am trying to run your code but cannot get the same result as in your paper. Actually it is far from the performance in your paper. Could you please upload the checkpoint? Thank you so much!

**Comment by GuodongQi** [comment]
Hi, for the network reason, I failed to upload the checkpoints. 
However, you can use other pretrained weights by standrad SGD  (i.e. pretrained without oblique manifold or RSGD).
Here is the [checkpoint](https://drive.google.com/file/d/15MFsig6pjXO7vZdo-1znJoXtHv4NY-AF/view?usp=sharing) from [TIM](https://github.com/mboudiaf/TIM).
